version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swyp-app
    restart: unless-stopped
    env_file:
      - ./src/main/resources/env.properties
    ports:
      - "8080:8080"
    network_mode: host
